export const projects = [
    {
        technologies: [],
        _id: "jkclfnheuriyoutcwe",
        title: "Fast food ",
        image: "https://sheysathya2.netlify.app/pizzas.svg",
        description: "its fast food management system website developed using react, express and mongoDB",
        link: "/",
    },
    {
        technologies: [],
        _id: "dhlakdjcnhfiposdu",
        title: "Ecommerce",
        image: "https://sheysathya2.netlify.app/ecommerce.svg",
        description: "its an Ecommerce management system website developed using react, express and mongoDB",
        link: "/",
    },
    {
        technologies: [],
        _id: "jdcjhahjpjhadhf",
        title: "Hotel",
        image: "https://sheysathya2.netlify.app/hotels.svg",
        description: "its Hotel Management system website developed using react, express and mongoDB",
        link: "/",
    },
    {
        technologies: [],
        _id: "jkclfnheuriyoutcwe",
        title: "Jobs ",
        image: "https://sheysathya2.netlify.app/jobs.svg",
        description: "its fast food management system website developed using react, express and mongoDB",
        link: "/",
    },
    {
        technologies: [],
        _id: "dhlakdjcnhfiposdu",
        title: "Social Media",
        image: "https://sheysathya2.netlify.app/socialmedia.svg",
        description: "its an Ecommerce management system website developed using react, express and mongoDB",
        link: "/",
    },
    {
        technologies: [],
        _id: "jdcjhahjpjhadhf",
        title: "Cars",
        image: "https://sheysathya2.netlify.app/cars.svg",
        description: "its Hotel Management system website developed using react, express and mongoDB",
        link: "/",
    },
]